spring:
  datasource:
    url: jdbc:postgresql://localhost:8080/history_details
    username: postgres
    password: admin123
  jpa:
    show-sql: true
    properties:
      hibernate :
        dialect : org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update
  application:
    name : consume-api

server:

  springdoc:
    swagger-ui.path: /swagger-ui/
  port: 9091
