    spring:
      datasource:
        url: jdbc:postgresql://localhost:8080/cars
        username: postgres
        password: admin123
      jpa:
        show-sql: true
        properties:
          hibernate :
            dialect : org.hibernate.dialect.PostgreSQLDialect
            ddl-auto: update
      application:
        name : consume-api

    server:

      springdoc:
          swagger-ui.path: /swagger-ui/
      port: 8081


    integration:
      creditUrl: http://localhost:9092/api/getCreditHistory
      ipsUrl: http://localhost:9093/api/crimeHistory
      carHistoryUrl: http://localhost:8082/api/carHistory
      historyByPanUrl: http://localhost:9091/api/getHistoryByPanNo
      historyDetailsUrl: http://localhost:9091/api/getHistory
      creditByPanUrl: http://localhost:9091/api/getHistoryByPanNo
